### ISSUE TITLE
Scroll bar not showing

### ISSUE THREAD

**Issue by AmandaBSobrinho** [nikbrunner/obsidian-deep-work-theme#66]
**Describe the bug**
There is no scroll bar in any windows with this theme. This makes it difficult to scroll long documents, since you must use the mouse scroll all the time.

**To Reproduce**
1. Install theme
2. Notice that the scroll bar has vanished

**Expected behavior**
The scroll bar shouldn't disappear.

**Screenshots**
![2022-03-31_20-19](https://user-images.githubusercontent.com/16309667/161165344-26b21508-1c29-4b75-a905-3584f61b729c.png)

![2022-03-31_20-20](https://user-images.githubusercontent.com/16309667/161165356-e2c7d94d-dec4-4312-9144-029bd6c93d1a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04, Kali Linux 2021

**Comment by nikbrunner** [comment]
Hi there,
yeah that was an intentional choice, but I will disable this Setting for now and want to make it an optional setting in the future which I mentioned here: #67 

Until then, if somebody is stumbling over this thread in the future, that the scrollbar is visible again, please use the "Hider" plugin from the MarketPlace. :)
